# Generated by Django 5.2.13 on 2026-05-07 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="target_stock",
            field=models.PositiveIntegerField(
                default=100, help_text="Reference level for 30% low stock alerts"
            ),
        ),
    ]
