# Generated by Django 5.2 on 2026-04-26 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="draft_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="invoices/drafts/"
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="voice_record",
            field=models.FileField(blank=True, null=True, upload_to="invoices/voice/"),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="invoice_number",
            field=models.CharField(
                blank=True,
                help_text="Auto-generated if left blank (e.g., YB-2026-0001)",
                max_length=50,
                unique=True,
            ),
        ),
    ]
