# Generated by Django 5.2 on 2026-04-26 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_invoice_draft_image_invoice_voice_record_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="email",
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
