# Generated by Django 5.2.13 on 2026-05-03 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_customer_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="is_gbese",
            field=models.BooleanField(
                default=False, help_text="Mark as debt if unpaid"
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="public_token",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
