# Generated by Django 5.2 on 2026-05-18 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_customer_user_invoice_user_product_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="industry",
            field=models.CharField(
                blank=True,
                choices=[
                    ("retail", "Retail / Shop"),
                    ("services", "Professional Services"),
                    ("manufacturing", "Manufacturing"),
                    ("other", "Other"),
                ],
                max_length=100,
            ),
        ),
    ]
