# Generated by Django 5.2.14 on 2026-05-20 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_profile_industry"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="invoice_template",
            field=models.CharField(
                choices=[
                    ("classic", "Classic"),
                    ("modern", "Modern"),
                    ("minimalist", "Minimalist"),
                ],
                default="classic",
                max_length=20,
            ),
        ),
    ]
