# Generated by Django 5.2.14 on 2026-05-20 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_profile_invoice_template"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="contact_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="primary_products",
            field=models.TextField(
                blank=True, help_text="Comma separated list of products/services"
            ),
        ),
    ]
