# Generated by Django 5.2.14 on 2026-05-25 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_profile_contact_email_profile_primary_products"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="trial_biz_address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="trial_biz_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="trial_biz_phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
